spring:
  datasource:
    url: ec2-54-247-79-178.eu-west-1.compute.amazonaws.com
    username: rtknfunosgiyku
    password: a940bf111cd960b9708e98dbcbdb98cf45e12cc4bbba54d35dac2464ecee59ab
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual-creation: true
  cloud:
    discovery:
      enabled: true
  application:
    name: builder-service

server:
  port: 9096

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: ${server.port}
    health-check-url: https://reservefast-builder.herokuapp.com/actuator/health
    home-page-url: https://reservefast-builder.herokuapp.com
    status-page-url: https://reservefast-builder.herokuapp.com/info
  client:
    serviceUrl:
      defaultZone: https://reservefast-eureka.herokuapp.com/eureka
    register-with-eureka: true
    fetch-registry: true